apiVersion: v1
kind: Service
metadata:
  name: client-cip-srv
spec:
  type: ClusterIP
  selector:
    app: client
  ports:
  - name: client 
    protocol: TCP
    port: 3000 # Port of the service
    targetPort: 3000 # Port of the "client service". They can also not be equal
