apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-bus-depl
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: event-bus # Search for a pod with a event-bus label
  template:
    metadata:
      labels:
        app: event-bus # Asign a label (equal to the one in matchLabels) to the pod
    spec:
      containers:
        - name: event-bus 
          image: microservices:event-bus
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"