apiVersion: v1
kind: Service
metadata:
  name: event-bus-cip-srv
spec:
  type: ClusterIP
  selector:
    app: event-bus
  ports:
  - name: event-bus 
    protocol: TCP
    port: 4005 # Port of the service
    targetPort: 4005 # Port of the "event-bus service". They can also not be equal
