apiVersion: networking.k8s.io/v1   # API version for Ingress resources (v1 is required from Kubernetes 1.22+)
kind: Ingress                       # Declares that this resource is an Ingress
metadata:
  name: ingress-srv  
  annotations: 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"                # Name of the Ingress resource
spec:
  ingressClassName: nginx            # Specifies the Ingress controller to use (nginx in this case)
  rules:                             # List of routing rules
    - host: posts.com                # Domain name that this rule applies to
      http:                          # HTTP routing configuration
        paths:                       # List of paths under the given host
          - path: /posts/create             # URL path to match
            pathType: Prefix         # Match all paths that start with "/posts"
            backend:                 # Defines where traffic should be sent
              service:               # Backend is a Kubernetes Service
                name: posts-cip-srv  # Name of the Service to route traffic to
                port:
                  number: 4000       # Port on the Service to forward requests
          - path: /posts 
            pathType: Prefix 
            backend: 
              service: 
                name: query-cip-srv
                port: 
                  number: 4002
          - path: /posts/?(.*)/comments
            pathType: ImplementationSpecific
            backend: 
              service: 
                name: comments-cip-srv
                port: 
                  number: 4001
          - path: /?(.*)
            pathType: ImplementationSpecific 
            backend:
              service: 
                name: client-cip-srv
                port: 
                  number: 3000
