apiVersion: v1
kind: Service
metadata:
  name: posts-cip-srv
spec:
  type: ClusterIP
  selector:
    app: posts
  ports:
  - name: posts 
    protocol: TCP
    port: 4000 # Port of the service
    targetPort: 4000 # Port of the "posts service". They can also not be equal
