apiVersion: v1
kind: Service
metadata:
  name: query-cip-srv
spec:
  type: ClusterIP
  selector:
    app: query
  ports:
  - name: query 
    protocol: TCP
    port: 4002 # Port of the service
    targetPort: 4002 # Port of the "query service". They can also not be equal
