apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-depl
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: query # Search for a pod with a query label
  template:
    metadata:
      labels:
        app: query # Asign a label (equal to the one in matchLabels) to the pod
    spec:
      containers:
        - name: query 
          image: thomastheprogrammer/query-service:dev
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
